__Вариант 26__

__№1__


Задания: 


$R = ||A \cdot B \cdot c|| - || d ||$

In [2]:
import numpy as np

In [3]:
A = np.array([
    [1, 2, 8],
    [4, 2, 3]
])

B = np.array([
    [7, 1],
    [4, 4],
    [1, 4]
])

c = np.array([
    [5],
    [9]
])

d = np.array([
    [3],
    [5],
    [6]
])

Результат __неопределен__, так как $||A \cdot B \cdot c||$ - матрица размера 1x2:

In [10]:
A@B@c

array([[484],
       [411]])

а вектор d - 1x3

In [4]:
R = A@B@c - d

ValueError: operands could not be broadcast together with shapes (2,1) (3,1) 


__№2__



Решите систему линейных алгебраических уравнений (СЛАУ) методом обратной матрицы:


х1+2х2+3х3=4

2х1+х2-х3=3

3х1+3х2+2х3=7

In [22]:
A = np.array([
    [1, 2, 3],
    [2, 1, -1],
    [3, 3, 2]
])

In [23]:
A

array([[ 1,  2,  3],
       [ 2,  1, -1],
       [ 3,  3,  2]])

In [24]:
b = np.array([4, 3, 7]).T

__Решение__

In [25]:
x = np.linalg.inv(A).dot(b)
print(x)

[ 16. -16.   0.]


__Проверка не пройдена:__

In [26]:
A@x

array([-16.,  16.,   0.])

__Матрица коэффициентов вырождена__ => метод обратной матрицы неприменим!

In [30]:
np.linalg.det(A)

5.551115123125763e-16

In [29]:
np.linalg.inv(A)@A

array([[  7.,   3.,   0.],
       [-12.,  -4.,   8.],
       [  3.,   1.,  -2.]])