__Вариант 6__

___

__№1__


Задания: 


$R = ||A \cdot B \cdot c + B^T \cdot d ||$

In [2]:
import numpy as np

In [4]:
A = np.array([
    [7, 8, 6],
    [5, 1, 7]
])

B = np.array([
    [6, 7],
    [7, 6],
    [9, 1]
])

c = np.array([
    [6],
    [9]
])

d = np.array([
    [4],
    [9],
    [3]
])

In [5]:
R = A@B@c + B.T@d

__Полученная матрица__

In [9]:
print(R)

[[1953]
 [1117]]


___

__№2__



Решите систему линейных алгебраических уравнений (СЛАУ) методом обратной матрицы:


* 8x1– x2 – 6x3 = 4 
* –3x1 + 8x2 – 2x3 = 5 
* – x1 – 10x3 = –6

In [10]:
A = np.array([
    [8, -1, -6],
    [-3, 8, -2],
    [-1, 0, -10]
])

In [11]:
A

array([[  8,  -1,  -6],
       [ -3,   8,  -2],
       [ -1,   0, -10]])

In [12]:
b = np.array([4, 5, -6]).T

__Решение__

In [14]:
x = np.linalg.inv(A).dot(b)
print(x)

[1.01515152 1.13030303 0.49848485]


In [16]:
A@x

array([ 4.,  5., -6.])