# №1 (Номер 49 - Вариант 4)

Задания: 

$ R = B^T \cdot A^T + C$

In [2]:
import numpy as np

In [6]:
A = np.array([
    [6,1, 2],
    [4, 1, 9]
])

B = np.array([
    [1, 2],
    [6, 8],
    [1, 2]
])

C = np.array([
    [1, 2],
    [6, 8]
])

In [9]:
R = B.T@A.T + C

## Ответ

In [20]:
R

array([[15, 21],
       [30, 42]])

# №2

Решите систему линейных алгебраических уравнений (СЛАУ) методом обратной матрицы:

$
\begin{cases}
– 8x_1  – 5x_2 – 3x_3 = –7 \\
x_1  – 6x_2 +   x_3 = –6 \\ 
10 x_3 =  6 
\end{cases}
$

In [12]:
A = np.array([
    [-8, -5, -3],
    [1, -6, 1],
    [0, 0, 10]
])

In [13]:
A

array([[-8, -5, -3],
       [ 1, -6,  1],
       [ 0,  0, 10]])

In [16]:
b = np.array([-7, -6, 6]).T

## Ответ

In [18]:
x = np.linalg.inv(A).dot(b)
x

array([-0.03396226,  1.09433962,  0.6       ])