# Вариант 2



# Задание 1

$ R = B \cdot c + A^T \cdot d$

In [1]:
import numpy as np

In [2]:
A = np.array([
    [6,1, 2],
    [4, 1, 9],
    [7, 8, 3]
])

B = np.array([
    [4,6, 9],
    [3, 8, 3],
    [4, 3, 4]
])

c = np.array([
    [2],
    [6],
    [3]
])

d = np.array([
    [4],
    [1],
    [2]
])

In [3]:
R = B@c + A.T@d

## Ответ

In [4]:
R

array([[113],
       [ 84],
       [ 61]])

# №2

Решите систему линейных алгебраических уравнений (СЛАУ) методом обратной матрицы:

$
\begin{cases}
– 7x_1  – 3x_2 – 2x_3 = –7 \\
-3x_1  – 5x_2 - x_3 = –5 \\ 
-x_1  – 3x_2 - 5x_3 = –5
\end{cases}
$

In [5]:
A = np.array([
    [-7, -3, -2],
    [-3, -5, -1],
    [-1, -3, -5]
])

In [6]:
A

array([[-7, -3, -2],
       [-3, -5, -1],
       [-1, -3, -5]])

Матрица А невырождена, метод применим

In [7]:
b = np.array([-7, -5, 5]).T

## Ответ

In [8]:
x = np.linalg.inv(A).dot(b)
x

array([ 1.2,  0.6, -1.6])